# Generated by Django 2.2.3 on 2019-07-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('C_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateadvets',
            options={'ordering': ['id'], 'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
    ]
